/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAddFundsRouteImport } from './routes/_authenticated.add-funds'
import { Route as AuthenticatedBalanceHistoryRouteImport } from './routes/_authenticated.balance-history'
import { Route as AuthenticatedCreateOrderRouteImport } from './routes/_authenticated.create-order'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedInstallAppRouteImport } from './routes/_authenticated.install-app'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated.menu'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated.orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedReferRouteImport } from './routes/_authenticated.refer'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated.services'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated.support'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated.transactions'
import { Route as ManagementIndexRouteImport } from './routes/management.index'
import { Route as ManagementApiLogsRouteImport } from './routes/management.api-logs'
import { Route as ManagementCategoriesRouteImport } from './routes/management.categories'
import { Route as ManagementLoginRouteImport } from './routes/management.login'
import { Route as ManagementManualOrdersRouteImport } from './routes/management.manual-orders'
import { Route as ManagementManualServicesRouteImport } from './routes/management.manual-services'
import { Route as ManagementMappingRouteImport } from './routes/management.mapping'
import { Route as ManagementOrdersRouteImport } from './routes/management.orders'
import { Route as ManagementPaymentsRouteImport } from './routes/management.payments'
import { Route as ManagementProviderServicesRouteImport } from './routes/management.provider-services'
import { Route as ManagementProvidersRouteImport } from './routes/management.providers'
import { Route as ManagementReferralsRouteImport } from './routes/management.referrals'
import { Route as ManagementReportsRouteImport } from './routes/management.reports'
import { Route as ManagementServicesRouteImport } from './routes/management.services'
import { Route as ManagementSettingsRouteImport } from './routes/management.settings'
import { Route as ManagementTransactionsRouteImport } from './routes/management.transactions'
import { Route as ManagementUsersRouteImport } from './routes/management.users'
import { Route as AuthenticatedOptionIdRouteImport } from './routes/_authenticated.option.$id'
import { Route as ApiPublicSyncOrdersRouteImport } from './routes/api/public/sync-orders'
import { Route as ManagementProvidersIndexRouteImport } from './routes/management.providers.index'
import { Route as ManagementProvidersIdRouteImport } from './routes/management.providers.$id'
import { Route as ManagementServicesIndexRouteImport } from './routes/management.services.index'
import { Route as ManagementServicesIdRouteImport } from './routes/management.services.$id'
import { Route as ManagementSettingsIndexRouteImport } from './routes/management.settings.index'
import { Route as ManagementSettingsAccountRouteImport } from './routes/management.settings.account'
import { Route as ManagementSettingsBrandingRouteImport } from './routes/management.settings.branding'
import { Route as ManagementSettingsCurrencyRouteImport } from './routes/management.settings.currency'
import { Route as ManagementTestsConsistencyRouteImport } from './routes/management.tests.consistency'
import { Route as ManagementProvidersIdIndexRouteImport } from './routes/management.providers.$id.index'
import { Route as ManagementProvidersIdLogsRouteImport } from './routes/management.providers.$id.logs'
import { Route as ManagementProvidersIdServicesRouteImport } from './routes/management.providers.$id.services'
import { Route as ManagementProvidersIdSettingsRouteImport } from './routes/management.providers.$id.settings'
import { Route as ApiPublicPaymentsBharatpayCallbackRouteImport } from './routes/api/public/payments/bharatpay/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddFundsRoute = AuthenticatedAddFundsRouteImport.update({
  id: '/add-funds',
  path: '/add-funds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBalanceHistoryRoute =
  AuthenticatedBalanceHistoryRouteImport.update({
    id: '/balance-history',
    path: '/balance-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCreateOrderRoute =
  AuthenticatedCreateOrderRouteImport.update({
    id: '/create-order',
    path: '/create-order',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstallAppRoute = AuthenticatedInstallAppRouteImport.update({
  id: '/install-app',
  path: '/install-app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferRoute = AuthenticatedReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementApiLogsRoute = ManagementApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementCategoriesRoute = ManagementCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementLoginRoute = ManagementLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementManualOrdersRoute = ManagementManualOrdersRouteImport.update({
  id: '/manual-orders',
  path: '/manual-orders',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementManualServicesRoute =
  ManagementManualServicesRouteImport.update({
    id: '/manual-services',
    path: '/manual-services',
    getParentRoute: () => ManagementRoute,
  } as any)
const ManagementMappingRoute = ManagementMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementOrdersRoute = ManagementOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementPaymentsRoute = ManagementPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementProviderServicesRoute =
  ManagementProviderServicesRouteImport.update({
    id: '/provider-services',
    path: '/provider-services',
    getParentRoute: () => ManagementRoute,
  } as any)
const ManagementProvidersRoute = ManagementProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementReferralsRoute = ManagementReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementReportsRoute = ManagementReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementServicesRoute = ManagementServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementSettingsRoute = ManagementSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementTransactionsRoute = ManagementTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ManagementRoute,
} as any)
const ManagementUsersRoute = ManagementUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagementRoute,
} as any)
const AuthenticatedOptionIdRoute = AuthenticatedOptionIdRouteImport.update({
  id: '/option/$id',
  path: '/option/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSyncOrdersRoute = ApiPublicSyncOrdersRouteImport.update({
  id: '/api/public/sync-orders',
  path: '/api/public/sync-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementProvidersIndexRoute =
  ManagementProvidersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagementProvidersRoute,
  } as any)
const ManagementProvidersIdRoute = ManagementProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ManagementProvidersRoute,
} as any)
const ManagementServicesIndexRoute = ManagementServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementServicesRoute,
} as any)
const ManagementServicesIdRoute = ManagementServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ManagementServicesRoute,
} as any)
const ManagementSettingsIndexRoute = ManagementSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementSettingsRoute,
} as any)
const ManagementSettingsAccountRoute =
  ManagementSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ManagementSettingsRoute,
  } as any)
const ManagementSettingsBrandingRoute =
  ManagementSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => ManagementSettingsRoute,
  } as any)
const ManagementSettingsCurrencyRoute =
  ManagementSettingsCurrencyRouteImport.update({
    id: '/currency',
    path: '/currency',
    getParentRoute: () => ManagementSettingsRoute,
  } as any)
const ManagementTestsConsistencyRoute =
  ManagementTestsConsistencyRouteImport.update({
    id: '/tests/consistency',
    path: '/tests/consistency',
    getParentRoute: () => ManagementRoute,
  } as any)
const ManagementProvidersIdIndexRoute =
  ManagementProvidersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagementProvidersIdRoute,
  } as any)
const ManagementProvidersIdLogsRoute =
  ManagementProvidersIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => ManagementProvidersIdRoute,
  } as any)
const ManagementProvidersIdServicesRoute =
  ManagementProvidersIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => ManagementProvidersIdRoute,
  } as any)
const ManagementProvidersIdSettingsRoute =
  ManagementProvidersIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ManagementProvidersIdRoute,
  } as any)
const ApiPublicPaymentsBharatpayCallbackRoute =
  ApiPublicPaymentsBharatpayCallbackRouteImport.update({
    id: '/api/public/payments/bharatpay/callback',
    path: '/api/public/payments/bharatpay/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRouteWithChildren
  '/register': typeof RegisterRoute
  '/add-funds': typeof AuthenticatedAddFundsRoute
  '/balance-history': typeof AuthenticatedBalanceHistoryRoute
  '/create-order': typeof AuthenticatedCreateOrderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/install-app': typeof AuthenticatedInstallAppRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/services': typeof AuthenticatedServicesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/management/api-logs': typeof ManagementApiLogsRoute
  '/management/categories': typeof ManagementCategoriesRoute
  '/management/login': typeof ManagementLoginRoute
  '/management/manual-orders': typeof ManagementManualOrdersRoute
  '/management/manual-services': typeof ManagementManualServicesRoute
  '/management/mapping': typeof ManagementMappingRoute
  '/management/orders': typeof ManagementOrdersRoute
  '/management/payments': typeof ManagementPaymentsRoute
  '/management/provider-services': typeof ManagementProviderServicesRoute
  '/management/providers': typeof ManagementProvidersRouteWithChildren
  '/management/referrals': typeof ManagementReferralsRoute
  '/management/reports': typeof ManagementReportsRoute
  '/management/services': typeof ManagementServicesRouteWithChildren
  '/management/settings': typeof ManagementSettingsRouteWithChildren
  '/management/transactions': typeof ManagementTransactionsRoute
  '/management/users': typeof ManagementUsersRoute
  '/management/': typeof ManagementIndexRoute
  '/option/$id': typeof AuthenticatedOptionIdRoute
  '/api/public/sync-orders': typeof ApiPublicSyncOrdersRoute
  '/management/providers/$id': typeof ManagementProvidersIdRouteWithChildren
  '/management/services/$id': typeof ManagementServicesIdRoute
  '/management/settings/account': typeof ManagementSettingsAccountRoute
  '/management/settings/branding': typeof ManagementSettingsBrandingRoute
  '/management/settings/currency': typeof ManagementSettingsCurrencyRoute
  '/management/tests/consistency': typeof ManagementTestsConsistencyRoute
  '/management/providers/': typeof ManagementProvidersIndexRoute
  '/management/services/': typeof ManagementServicesIndexRoute
  '/management/settings/': typeof ManagementSettingsIndexRoute
  '/management/providers/$id/logs': typeof ManagementProvidersIdLogsRoute
  '/management/providers/$id/services': typeof ManagementProvidersIdServicesRoute
  '/management/providers/$id/settings': typeof ManagementProvidersIdSettingsRoute
  '/management/providers/$id/': typeof ManagementProvidersIdIndexRoute
  '/api/public/payments/bharatpay/callback': typeof ApiPublicPaymentsBharatpayCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-funds': typeof AuthenticatedAddFundsRoute
  '/balance-history': typeof AuthenticatedBalanceHistoryRoute
  '/create-order': typeof AuthenticatedCreateOrderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/install-app': typeof AuthenticatedInstallAppRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/services': typeof AuthenticatedServicesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/management/api-logs': typeof ManagementApiLogsRoute
  '/management/categories': typeof ManagementCategoriesRoute
  '/management/login': typeof ManagementLoginRoute
  '/management/manual-orders': typeof ManagementManualOrdersRoute
  '/management/manual-services': typeof ManagementManualServicesRoute
  '/management/mapping': typeof ManagementMappingRoute
  '/management/orders': typeof ManagementOrdersRoute
  '/management/payments': typeof ManagementPaymentsRoute
  '/management/provider-services': typeof ManagementProviderServicesRoute
  '/management/referrals': typeof ManagementReferralsRoute
  '/management/reports': typeof ManagementReportsRoute
  '/management/transactions': typeof ManagementTransactionsRoute
  '/management/users': typeof ManagementUsersRoute
  '/management': typeof ManagementIndexRoute
  '/option/$id': typeof AuthenticatedOptionIdRoute
  '/api/public/sync-orders': typeof ApiPublicSyncOrdersRoute
  '/management/services/$id': typeof ManagementServicesIdRoute
  '/management/settings/account': typeof ManagementSettingsAccountRoute
  '/management/settings/branding': typeof ManagementSettingsBrandingRoute
  '/management/settings/currency': typeof ManagementSettingsCurrencyRoute
  '/management/tests/consistency': typeof ManagementTestsConsistencyRoute
  '/management/providers': typeof ManagementProvidersIndexRoute
  '/management/services': typeof ManagementServicesIndexRoute
  '/management/settings': typeof ManagementSettingsIndexRoute
  '/management/providers/$id/logs': typeof ManagementProvidersIdLogsRoute
  '/management/providers/$id/services': typeof ManagementProvidersIdServicesRoute
  '/management/providers/$id/settings': typeof ManagementProvidersIdSettingsRoute
  '/management/providers/$id': typeof ManagementProvidersIdIndexRoute
  '/api/public/payments/bharatpay/callback': typeof ApiPublicPaymentsBharatpayCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/management': typeof ManagementRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/add-funds': typeof AuthenticatedAddFundsRoute
  '/_authenticated/balance-history': typeof AuthenticatedBalanceHistoryRoute
  '/_authenticated/create-order': typeof AuthenticatedCreateOrderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/install-app': typeof AuthenticatedInstallAppRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/refer': typeof AuthenticatedReferRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/management/api-logs': typeof ManagementApiLogsRoute
  '/management/categories': typeof ManagementCategoriesRoute
  '/management/login': typeof ManagementLoginRoute
  '/management/manual-orders': typeof ManagementManualOrdersRoute
  '/management/manual-services': typeof ManagementManualServicesRoute
  '/management/mapping': typeof ManagementMappingRoute
  '/management/orders': typeof ManagementOrdersRoute
  '/management/payments': typeof ManagementPaymentsRoute
  '/management/provider-services': typeof ManagementProviderServicesRoute
  '/management/providers': typeof ManagementProvidersRouteWithChildren
  '/management/referrals': typeof ManagementReferralsRoute
  '/management/reports': typeof ManagementReportsRoute
  '/management/services': typeof ManagementServicesRouteWithChildren
  '/management/settings': typeof ManagementSettingsRouteWithChildren
  '/management/transactions': typeof ManagementTransactionsRoute
  '/management/users': typeof ManagementUsersRoute
  '/management/': typeof ManagementIndexRoute
  '/_authenticated/option/$id': typeof AuthenticatedOptionIdRoute
  '/api/public/sync-orders': typeof ApiPublicSyncOrdersRoute
  '/management/providers/$id': typeof ManagementProvidersIdRouteWithChildren
  '/management/services/$id': typeof ManagementServicesIdRoute
  '/management/settings/account': typeof ManagementSettingsAccountRoute
  '/management/settings/branding': typeof ManagementSettingsBrandingRoute
  '/management/settings/currency': typeof ManagementSettingsCurrencyRoute
  '/management/tests/consistency': typeof ManagementTestsConsistencyRoute
  '/management/providers/': typeof ManagementProvidersIndexRoute
  '/management/services/': typeof ManagementServicesIndexRoute
  '/management/settings/': typeof ManagementSettingsIndexRoute
  '/management/providers/$id/logs': typeof ManagementProvidersIdLogsRoute
  '/management/providers/$id/services': typeof ManagementProvidersIdServicesRoute
  '/management/providers/$id/settings': typeof ManagementProvidersIdSettingsRoute
  '/management/providers/$id/': typeof ManagementProvidersIdIndexRoute
  '/api/public/payments/bharatpay/callback': typeof ApiPublicPaymentsBharatpayCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/management'
    | '/register'
    | '/add-funds'
    | '/balance-history'
    | '/create-order'
    | '/dashboard'
    | '/install-app'
    | '/menu'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/services'
    | '/support'
    | '/transactions'
    | '/management/api-logs'
    | '/management/categories'
    | '/management/login'
    | '/management/manual-orders'
    | '/management/manual-services'
    | '/management/mapping'
    | '/management/orders'
    | '/management/payments'
    | '/management/provider-services'
    | '/management/providers'
    | '/management/referrals'
    | '/management/reports'
    | '/management/services'
    | '/management/settings'
    | '/management/transactions'
    | '/management/users'
    | '/management/'
    | '/option/$id'
    | '/api/public/sync-orders'
    | '/management/providers/$id'
    | '/management/services/$id'
    | '/management/settings/account'
    | '/management/settings/branding'
    | '/management/settings/currency'
    | '/management/tests/consistency'
    | '/management/providers/'
    | '/management/services/'
    | '/management/settings/'
    | '/management/providers/$id/logs'
    | '/management/providers/$id/services'
    | '/management/providers/$id/settings'
    | '/management/providers/$id/'
    | '/api/public/payments/bharatpay/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/add-funds'
    | '/balance-history'
    | '/create-order'
    | '/dashboard'
    | '/install-app'
    | '/menu'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/services'
    | '/support'
    | '/transactions'
    | '/management/api-logs'
    | '/management/categories'
    | '/management/login'
    | '/management/manual-orders'
    | '/management/manual-services'
    | '/management/mapping'
    | '/management/orders'
    | '/management/payments'
    | '/management/provider-services'
    | '/management/referrals'
    | '/management/reports'
    | '/management/transactions'
    | '/management/users'
    | '/management'
    | '/option/$id'
    | '/api/public/sync-orders'
    | '/management/services/$id'
    | '/management/settings/account'
    | '/management/settings/branding'
    | '/management/settings/currency'
    | '/management/tests/consistency'
    | '/management/providers'
    | '/management/services'
    | '/management/settings'
    | '/management/providers/$id/logs'
    | '/management/providers/$id/services'
    | '/management/providers/$id/settings'
    | '/management/providers/$id'
    | '/api/public/payments/bharatpay/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/management'
    | '/register'
    | '/_authenticated/add-funds'
    | '/_authenticated/balance-history'
    | '/_authenticated/create-order'
    | '/_authenticated/dashboard'
    | '/_authenticated/install-app'
    | '/_authenticated/menu'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/refer'
    | '/_authenticated/services'
    | '/_authenticated/support'
    | '/_authenticated/transactions'
    | '/management/api-logs'
    | '/management/categories'
    | '/management/login'
    | '/management/manual-orders'
    | '/management/manual-services'
    | '/management/mapping'
    | '/management/orders'
    | '/management/payments'
    | '/management/provider-services'
    | '/management/providers'
    | '/management/referrals'
    | '/management/reports'
    | '/management/services'
    | '/management/settings'
    | '/management/transactions'
    | '/management/users'
    | '/management/'
    | '/_authenticated/option/$id'
    | '/api/public/sync-orders'
    | '/management/providers/$id'
    | '/management/services/$id'
    | '/management/settings/account'
    | '/management/settings/branding'
    | '/management/settings/currency'
    | '/management/tests/consistency'
    | '/management/providers/'
    | '/management/services/'
    | '/management/settings/'
    | '/management/providers/$id/logs'
    | '/management/providers/$id/services'
    | '/management/providers/$id/settings'
    | '/management/providers/$id/'
    | '/api/public/payments/bharatpay/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ApiPublicSyncOrdersRoute: typeof ApiPublicSyncOrdersRoute
  ApiPublicPaymentsBharatpayCallbackRoute: typeof ApiPublicPaymentsBharatpayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add-funds': {
      id: '/_authenticated/add-funds'
      path: '/add-funds'
      fullPath: '/add-funds'
      preLoaderRoute: typeof AuthenticatedAddFundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/balance-history': {
      id: '/_authenticated/balance-history'
      path: '/balance-history'
      fullPath: '/balance-history'
      preLoaderRoute: typeof AuthenticatedBalanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-order': {
      id: '/_authenticated/create-order'
      path: '/create-order'
      fullPath: '/create-order'
      preLoaderRoute: typeof AuthenticatedCreateOrderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/install-app': {
      id: '/_authenticated/install-app'
      path: '/install-app'
      fullPath: '/install-app'
      preLoaderRoute: typeof AuthenticatedInstallAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refer': {
      id: '/_authenticated/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/management/': {
      id: '/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/api-logs': {
      id: '/management/api-logs'
      path: '/api-logs'
      fullPath: '/management/api-logs'
      preLoaderRoute: typeof ManagementApiLogsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/categories': {
      id: '/management/categories'
      path: '/categories'
      fullPath: '/management/categories'
      preLoaderRoute: typeof ManagementCategoriesRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/login': {
      id: '/management/login'
      path: '/login'
      fullPath: '/management/login'
      preLoaderRoute: typeof ManagementLoginRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/manual-orders': {
      id: '/management/manual-orders'
      path: '/manual-orders'
      fullPath: '/management/manual-orders'
      preLoaderRoute: typeof ManagementManualOrdersRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/manual-services': {
      id: '/management/manual-services'
      path: '/manual-services'
      fullPath: '/management/manual-services'
      preLoaderRoute: typeof ManagementManualServicesRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/mapping': {
      id: '/management/mapping'
      path: '/mapping'
      fullPath: '/management/mapping'
      preLoaderRoute: typeof ManagementMappingRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/orders': {
      id: '/management/orders'
      path: '/orders'
      fullPath: '/management/orders'
      preLoaderRoute: typeof ManagementOrdersRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/payments': {
      id: '/management/payments'
      path: '/payments'
      fullPath: '/management/payments'
      preLoaderRoute: typeof ManagementPaymentsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/provider-services': {
      id: '/management/provider-services'
      path: '/provider-services'
      fullPath: '/management/provider-services'
      preLoaderRoute: typeof ManagementProviderServicesRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/providers': {
      id: '/management/providers'
      path: '/providers'
      fullPath: '/management/providers'
      preLoaderRoute: typeof ManagementProvidersRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/referrals': {
      id: '/management/referrals'
      path: '/referrals'
      fullPath: '/management/referrals'
      preLoaderRoute: typeof ManagementReferralsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/reports': {
      id: '/management/reports'
      path: '/reports'
      fullPath: '/management/reports'
      preLoaderRoute: typeof ManagementReportsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/services': {
      id: '/management/services'
      path: '/services'
      fullPath: '/management/services'
      preLoaderRoute: typeof ManagementServicesRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/settings': {
      id: '/management/settings'
      path: '/settings'
      fullPath: '/management/settings'
      preLoaderRoute: typeof ManagementSettingsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/transactions': {
      id: '/management/transactions'
      path: '/transactions'
      fullPath: '/management/transactions'
      preLoaderRoute: typeof ManagementTransactionsRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/users': {
      id: '/management/users'
      path: '/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof ManagementUsersRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/_authenticated/option/$id': {
      id: '/_authenticated/option/$id'
      path: '/option/$id'
      fullPath: '/option/$id'
      preLoaderRoute: typeof AuthenticatedOptionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sync-orders': {
      id: '/api/public/sync-orders'
      path: '/api/public/sync-orders'
      fullPath: '/api/public/sync-orders'
      preLoaderRoute: typeof ApiPublicSyncOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/providers/': {
      id: '/management/providers/'
      path: '/'
      fullPath: '/management/providers/'
      preLoaderRoute: typeof ManagementProvidersIndexRouteImport
      parentRoute: typeof ManagementProvidersRoute
    }
    '/management/providers/$id': {
      id: '/management/providers/$id'
      path: '/$id'
      fullPath: '/management/providers/$id'
      preLoaderRoute: typeof ManagementProvidersIdRouteImport
      parentRoute: typeof ManagementProvidersRoute
    }
    '/management/services/': {
      id: '/management/services/'
      path: '/'
      fullPath: '/management/services/'
      preLoaderRoute: typeof ManagementServicesIndexRouteImport
      parentRoute: typeof ManagementServicesRoute
    }
    '/management/services/$id': {
      id: '/management/services/$id'
      path: '/$id'
      fullPath: '/management/services/$id'
      preLoaderRoute: typeof ManagementServicesIdRouteImport
      parentRoute: typeof ManagementServicesRoute
    }
    '/management/settings/': {
      id: '/management/settings/'
      path: '/'
      fullPath: '/management/settings/'
      preLoaderRoute: typeof ManagementSettingsIndexRouteImport
      parentRoute: typeof ManagementSettingsRoute
    }
    '/management/settings/account': {
      id: '/management/settings/account'
      path: '/account'
      fullPath: '/management/settings/account'
      preLoaderRoute: typeof ManagementSettingsAccountRouteImport
      parentRoute: typeof ManagementSettingsRoute
    }
    '/management/settings/branding': {
      id: '/management/settings/branding'
      path: '/branding'
      fullPath: '/management/settings/branding'
      preLoaderRoute: typeof ManagementSettingsBrandingRouteImport
      parentRoute: typeof ManagementSettingsRoute
    }
    '/management/settings/currency': {
      id: '/management/settings/currency'
      path: '/currency'
      fullPath: '/management/settings/currency'
      preLoaderRoute: typeof ManagementSettingsCurrencyRouteImport
      parentRoute: typeof ManagementSettingsRoute
    }
    '/management/tests/consistency': {
      id: '/management/tests/consistency'
      path: '/tests/consistency'
      fullPath: '/management/tests/consistency'
      preLoaderRoute: typeof ManagementTestsConsistencyRouteImport
      parentRoute: typeof ManagementRoute
    }
    '/management/providers/$id/': {
      id: '/management/providers/$id/'
      path: '/'
      fullPath: '/management/providers/$id/'
      preLoaderRoute: typeof ManagementProvidersIdIndexRouteImport
      parentRoute: typeof ManagementProvidersIdRoute
    }
    '/management/providers/$id/logs': {
      id: '/management/providers/$id/logs'
      path: '/logs'
      fullPath: '/management/providers/$id/logs'
      preLoaderRoute: typeof ManagementProvidersIdLogsRouteImport
      parentRoute: typeof ManagementProvidersIdRoute
    }
    '/management/providers/$id/services': {
      id: '/management/providers/$id/services'
      path: '/services'
      fullPath: '/management/providers/$id/services'
      preLoaderRoute: typeof ManagementProvidersIdServicesRouteImport
      parentRoute: typeof ManagementProvidersIdRoute
    }
    '/management/providers/$id/settings': {
      id: '/management/providers/$id/settings'
      path: '/settings'
      fullPath: '/management/providers/$id/settings'
      preLoaderRoute: typeof ManagementProvidersIdSettingsRouteImport
      parentRoute: typeof ManagementProvidersIdRoute
    }
    '/api/public/payments/bharatpay/callback': {
      id: '/api/public/payments/bharatpay/callback'
      path: '/api/public/payments/bharatpay/callback'
      fullPath: '/api/public/payments/bharatpay/callback'
      preLoaderRoute: typeof ApiPublicPaymentsBharatpayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddFundsRoute: typeof AuthenticatedAddFundsRoute
  AuthenticatedBalanceHistoryRoute: typeof AuthenticatedBalanceHistoryRoute
  AuthenticatedCreateOrderRoute: typeof AuthenticatedCreateOrderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstallAppRoute: typeof AuthenticatedInstallAppRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferRoute: typeof AuthenticatedReferRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedOptionIdRoute: typeof AuthenticatedOptionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddFundsRoute: AuthenticatedAddFundsRoute,
  AuthenticatedBalanceHistoryRoute: AuthenticatedBalanceHistoryRoute,
  AuthenticatedCreateOrderRoute: AuthenticatedCreateOrderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstallAppRoute: AuthenticatedInstallAppRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferRoute: AuthenticatedReferRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedOptionIdRoute: AuthenticatedOptionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ManagementProvidersIdRouteChildren {
  ManagementProvidersIdLogsRoute: typeof ManagementProvidersIdLogsRoute
  ManagementProvidersIdServicesRoute: typeof ManagementProvidersIdServicesRoute
  ManagementProvidersIdSettingsRoute: typeof ManagementProvidersIdSettingsRoute
  ManagementProvidersIdIndexRoute: typeof ManagementProvidersIdIndexRoute
}

const ManagementProvidersIdRouteChildren: ManagementProvidersIdRouteChildren = {
  ManagementProvidersIdLogsRoute: ManagementProvidersIdLogsRoute,
  ManagementProvidersIdServicesRoute: ManagementProvidersIdServicesRoute,
  ManagementProvidersIdSettingsRoute: ManagementProvidersIdSettingsRoute,
  ManagementProvidersIdIndexRoute: ManagementProvidersIdIndexRoute,
}

const ManagementProvidersIdRouteWithChildren =
  ManagementProvidersIdRoute._addFileChildren(
    ManagementProvidersIdRouteChildren,
  )

interface ManagementProvidersRouteChildren {
  ManagementProvidersIdRoute: typeof ManagementProvidersIdRouteWithChildren
  ManagementProvidersIndexRoute: typeof ManagementProvidersIndexRoute
}

const ManagementProvidersRouteChildren: ManagementProvidersRouteChildren = {
  ManagementProvidersIdRoute: ManagementProvidersIdRouteWithChildren,
  ManagementProvidersIndexRoute: ManagementProvidersIndexRoute,
}

const ManagementProvidersRouteWithChildren =
  ManagementProvidersRoute._addFileChildren(ManagementProvidersRouteChildren)

interface ManagementServicesRouteChildren {
  ManagementServicesIdRoute: typeof ManagementServicesIdRoute
  ManagementServicesIndexRoute: typeof ManagementServicesIndexRoute
}

const ManagementServicesRouteChildren: ManagementServicesRouteChildren = {
  ManagementServicesIdRoute: ManagementServicesIdRoute,
  ManagementServicesIndexRoute: ManagementServicesIndexRoute,
}

const ManagementServicesRouteWithChildren =
  ManagementServicesRoute._addFileChildren(ManagementServicesRouteChildren)

interface ManagementSettingsRouteChildren {
  ManagementSettingsAccountRoute: typeof ManagementSettingsAccountRoute
  ManagementSettingsBrandingRoute: typeof ManagementSettingsBrandingRoute
  ManagementSettingsCurrencyRoute: typeof ManagementSettingsCurrencyRoute
  ManagementSettingsIndexRoute: typeof ManagementSettingsIndexRoute
}

const ManagementSettingsRouteChildren: ManagementSettingsRouteChildren = {
  ManagementSettingsAccountRoute: ManagementSettingsAccountRoute,
  ManagementSettingsBrandingRoute: ManagementSettingsBrandingRoute,
  ManagementSettingsCurrencyRoute: ManagementSettingsCurrencyRoute,
  ManagementSettingsIndexRoute: ManagementSettingsIndexRoute,
}

const ManagementSettingsRouteWithChildren =
  ManagementSettingsRoute._addFileChildren(ManagementSettingsRouteChildren)

interface ManagementRouteChildren {
  ManagementApiLogsRoute: typeof ManagementApiLogsRoute
  ManagementCategoriesRoute: typeof ManagementCategoriesRoute
  ManagementLoginRoute: typeof ManagementLoginRoute
  ManagementManualOrdersRoute: typeof ManagementManualOrdersRoute
  ManagementManualServicesRoute: typeof ManagementManualServicesRoute
  ManagementMappingRoute: typeof ManagementMappingRoute
  ManagementOrdersRoute: typeof ManagementOrdersRoute
  ManagementPaymentsRoute: typeof ManagementPaymentsRoute
  ManagementProviderServicesRoute: typeof ManagementProviderServicesRoute
  ManagementProvidersRoute: typeof ManagementProvidersRouteWithChildren
  ManagementReferralsRoute: typeof ManagementReferralsRoute
  ManagementReportsRoute: typeof ManagementReportsRoute
  ManagementServicesRoute: typeof ManagementServicesRouteWithChildren
  ManagementSettingsRoute: typeof ManagementSettingsRouteWithChildren
  ManagementTransactionsRoute: typeof ManagementTransactionsRoute
  ManagementUsersRoute: typeof ManagementUsersRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  ManagementTestsConsistencyRoute: typeof ManagementTestsConsistencyRoute
}

const ManagementRouteChildren: ManagementRouteChildren = {
  ManagementApiLogsRoute: ManagementApiLogsRoute,
  ManagementCategoriesRoute: ManagementCategoriesRoute,
  ManagementLoginRoute: ManagementLoginRoute,
  ManagementManualOrdersRoute: ManagementManualOrdersRoute,
  ManagementManualServicesRoute: ManagementManualServicesRoute,
  ManagementMappingRoute: ManagementMappingRoute,
  ManagementOrdersRoute: ManagementOrdersRoute,
  ManagementPaymentsRoute: ManagementPaymentsRoute,
  ManagementProviderServicesRoute: ManagementProviderServicesRoute,
  ManagementProvidersRoute: ManagementProvidersRouteWithChildren,
  ManagementReferralsRoute: ManagementReferralsRoute,
  ManagementReportsRoute: ManagementReportsRoute,
  ManagementServicesRoute: ManagementServicesRouteWithChildren,
  ManagementSettingsRoute: ManagementSettingsRouteWithChildren,
  ManagementTransactionsRoute: ManagementTransactionsRoute,
  ManagementUsersRoute: ManagementUsersRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  ManagementTestsConsistencyRoute: ManagementTestsConsistencyRoute,
}

const ManagementRouteWithChildren = ManagementRoute._addFileChildren(
  ManagementRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ApiPublicSyncOrdersRoute: ApiPublicSyncOrdersRoute,
  ApiPublicPaymentsBharatpayCallbackRoute:
    ApiPublicPaymentsBharatpayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
