// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined

    if (typeof window !== 'undefined') {
      try {
        // 1. Try environment variable based key (fastest)
        const projectRef = import.meta.env['VITE_SUPABASE_URL']?.split('.')[0].split('//')[1];
        if (projectRef) {
          const sessionStr = localStorage.getItem(`sb-${projectRef}-auth-token`);
          if (sessionStr) {
            token = JSON.parse(sessionStr)?.access_token;
          }
        }

        // 2. Fallback to scanning localStorage for any supabase auth token (widest compatibility)
        if (!token) {
          const storageKey = Object.keys(localStorage).find(key => key.startsWith('sb-') && key.endsWith('-auth-token'));
          if (storageKey) {
            const sessionStr = localStorage.getItem(storageKey);
            if (sessionStr) {
              token = JSON.parse(sessionStr)?.access_token;
            }
          }
        }

        // 3. Last resort: direct client check (can be slow/async)
        if (!token) {
          const { data } = await supabase.auth.getSession();
          token = data.session?.access_token;
        }
      } catch (e) {
        // Silent fail for attacher
      }
    }
    
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
